const ADD_TODO = 'ADD_TODO';
const TOGGLE_TODO = 'TOGGLE_TODO';
const UPDATE_TODO = 'UPDATE_TODO';
const REMOVE_TODO = 'REMOVE_TODO';
const FILTER_TODO = 'FILTER_TODO';
const MARK_ALL_COMPLETED = 'MARK_ALL_COMPLETED';
const UPDATE_SEARCH_TERM = 'UPDATE_SEARCH_TERM';

export {
  ADD_TODO,
  TOGGLE_TODO,
  UPDATE_TODO,
  REMOVE_TODO,
  FILTER_TODO,
  MARK_ALL_COMPLETED,
  UPDATE_SEARCH_TERM,
};
